### ISSUE TITLE
Resizing markdown window mis-positions html.

### ISSUE THREAD

**Issue by greysonp** [miketoth/markdown_new_page#1]
If you resize the window so the markdown area is larger, this happens:
![screenshot 2015-02-16 23 34 03](https://cloud.githubusercontent.com/assets/1358731/6224670/847469f4-b634-11e4-8f37-10a4c498e072.png)

Putting the window back to normal size fixes this.

**Comment by miketoth** [comment]
oh noes. Imma fix that
